In [2]:
from matplotlib import pyplot as plt
import numpy as np
from PIL import Image
from scipy import spatial
loc = "images/"

In [3]:
img_path = loc + 'apple1.jpg'
im = Image.open(img_path)


In [45]:
# to maintain uniformity between images
im.thumbnail((100,100))
name = "apple1"
im.save(loc + name + "_p.jpg","JPEG")

In [4]:
im_array = np.array(im)
im_array[0,2]

array([255, 255, 255], dtype=uint8)

In [6]:
im_array.shape

(1500, 1500, 3)

In [48]:
for r in range(len(im_array)):
    for c in range(len(im_array[r])):
        if im_array[r,c][0]>150:
            #easy way to swap variables
            #x,y = y,x
            im_array[r,c][0],im_array[r,c][1] = im_array[r,c][1],im_array[r,c][0]

img = Image.fromarray(im_array)
img.save(loc + name + "_m.jpg","JPEG")

In [49]:
with open(loc + name + ".txt","w") as ifile:
    for row in im_array:
        ifile.write(str(row)+"\n")

In [50]:
#greyscale
im_gs = im.convert('L')
im_gs.save(loc + name + "_gs.jpg","JPEG")
im_array_gs = np.array(im_gs)
im_array_gs[50,50]

58

In [51]:
im_array_gs

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [55]:
#black white
threshold = 200
im_array_bw = im_array_gs.copy()
im_array_bw[im_array_bw > threshold] = 255
im_array_bw[im_array_bw <= threshold] = 0
im_bw = Image.fromarray(im_array_bw)
im_bw.save(loc + name + "_bw.jpg","JPEG")
im_array[50,50]

array([  4, 183,  15], dtype=uint8)

In [5]:
len(im_array)

1500

In [60]:
#cut apple
im_array_conv = im_array_gs.copy()
#im_array_conv[50, :] = 255

k = np.array([[0,1,0],[0,-1,1],[1,1,0]])
output = np.zeros_like(im_conv)

for r in range(len(im_array_conv)):
    for c in range(len(im_array_conv[r])):
        window = im_array_conv[r:r+len(k), c:c+len(k[0])]
        if window.shape != k.shape: continue
        window_conv = np.dot(window,k)
        output[r:r+len(k),c:c+len(k[0])] = window_conv


im_conv = Image.fromarray(im_array_conv)
im_conv.save(loc + name + "_conv.jpg","JPEG")