In [22]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import re
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer, WordNetLemmatizer
#Lets use TFIDF to get the numerical values for the text
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
review = pd.read_csv('H:\Imarticus\All_Classification\imdb-sentiments\\train.csv')
review.head(5)

text  sentiment
0  For a movie that gets no respect there sure ar...          0
1  Bizarre horror movie filled with famous faces ...          0
2  A solid, if unremarkable film. Matthau, as Ein...          0
3  It's a strange feeling to sit alone in a theat...          0
4  You probably all already know this by now, but...          0

In [8]:
review['sentiment'].value_counts()

1    12500
0    12500
Name: sentiment, dtype: int64

In [10]:
raw_data = review['text'].tolist()

In [18]:
def cleanText(text, removeStopwords=True, performStemming=True):
    
    #regex for removing non-alphanumeric characters and spaces
    remove_special_char = re.compile('r[^a-z\d]', re.IGNORECASE)
    #regex to replace all numerics
    replace_numerics = re.compile(r'\d+', re.IGNORECASE)
    text = remove_special_char.sub('', text)
    text = replace_numerics.sub('', text)

    stop_words = set(stopwords.words('english')) 
    stemmer = SnowballStemmer('english')
    lemmatizer = WordNetLemmatizer()
    
    #convert text to lowercase.
    text = text.lower().split()

    
    processedText = list()
    for word in text:        
        if removeStopwords:
            if word in stop_words:
                continue
        if performStemming:
            word = stemmer.stem(word)
            
        word = lemmatizer.lemmatize(word)
        word = lemmatizer.lemmatize(word, 'v')
            
        processedText.append(word)

    text = ' '.join(processedText)

    return text

In [33]:
pre_vector = [cleanText(review) for review in raw_data]

In [34]:
# create the transform
vectorizer = TfidfVectorizer()
# tokenize and build vocab
vectorizer.fit(pre_vector)
# summarize
#print(vectorizer.vocabulary_)
#print(vectorizer.idf_)
# encode document
X = vectorizer.transform(pre_vector)
# # summarize encoded vector
print(X.shape)
print(X.toarray())

(25000, 140183)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [36]:
X_train = X[0:20000]
print(X_train.shape)
X_test = X[20000:25000]
print(X_test.shape)

(20000, 140183)
(5000, 140183)


In [37]:
Y_train = review['sentiment'][0:20000]
print(Y_train.shape)
Y_test = review['sentiment'][20000:52000]
print(Y_test.shape)

(20000,)
(5000,)
